#!/bin/bash
# ──────────────────────────────────────────────
# NEXUS - Vercel Environment Variables Setup
# ──────────────────────────────────────────────
# Use this reference to configure env vars in Vercel.
# Option A: Copy-paste into Vercel Dashboard (> Settings > Environment Variables)
# Option B: Use vercel CLI (commands included at the bottom)
# ──────────────────────────────────────────────

ENV=${1:-production}
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║   NEXUS - Vercel Environment Variables          ║"
echo "║   Target environment: $ENV"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  REQUIRED (app won't start without these)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL"
echo "  Your Supabase project URL"
echo ""
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "  Supabase anonymous/public key"
echo ""
echo "SUPABASE_SERVICE_ROLE_KEY"
echo "  Supabase service role key (for admin operations)"
echo ""
echo "REDIS_HOST"
echo "  Redis host for BullMQ queue (Upstash, Redis Cloud, etc.)"
echo ""
echo "REDIS_PORT"
echo "  Redis port (default: 6379)"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  AI PIPELINE (required for search + embeddings)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OLLAMA_URL"
echo "  Ollama API URL"
echo "  Dev: http://localhost:11434"
echo "  Prod: https://your-ollama-server:11434"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  QUEUE & BACKFILL (optional - defaults shown)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "REDIS_PASSWORD"
echo "  Redis password (leave blank if none)"
echo ""
echo "REDIS_DB"
echo "  Redis database number (default: 0)"
echo ""
echo "BACKFILL_CRON"
echo "  Cron schedule for backfill (default: */15 * * * *)"
echo ""
echo "BACKFILL_BATCH"
echo "  Items per backfill scan (default: 200)"
echo ""
echo "BACKFILL_ENABLED"
echo "  Set to false to disable (default: true)"
echo ""
echo "WORKER_CONCURRENCY"
echo "  AI jobs per worker (default: 2)"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NOTIFICATIONS (optional - for critical alerts)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "SLACK_WEBHOOK_URL"
echo "  Slack incoming webhook URL"
echo ""
echo "DISCORD_WEBHOOK_URL"
echo "  Discord webhook URL"
echo ""
echo "RESEND_API_KEY"
echo "  Resend.com API key for email alerts"
echo ""
echo "ALERT_EMAIL_TO"
echo "  Alert recipient email address"
echo ""
echo "ALERT_EMAIL_FROM"
echo "  Alert sender (default: NEXUS Alerts <alerts@nexus.app>)"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  DEPLOYMENT (optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NEXT_PUBLIC_REDIS_HOST"
echo "  Redis hostname for status page display"
echo ""
echo "DATABASE_URL"
echo "  Postgres connection string for LISTEN/NOTIFY"
echo ""
echo "NEXUS_URL"
echo "  Override URL for notification links"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VERCOL CLI COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Requires Vercel CLI: npm i -g vercel && vercel login"
echo "# Replace <value> with actual values."
echo ""
echo "# --- Required: Supabase ---"
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL $ENV"
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY $ENV"
echo "vercel env add SUPABASE_SERVICE_ROLE_KEY $ENV"
echo ""
echo "# --- Required: Redis ---"
echo "vercel env add REDIS_HOST $ENV"
echo "vercel env add REDIS_PORT $ENV"
echo ""
echo "# --- AI Pipeline ---"
echo "vercel env add OLLAMA_URL $ENV"
echo ""
echo "# --- Queue & Backfill ---"
echo "vercel env add REDIS_PASSWORD $ENV"
echo "vercel env add REDIS_DB $ENV"
echo "vercel env add BACKFILL_CRON $ENV"
echo "vercel env add BACKFILL_BATCH $ENV"
echo "vercel env add BACKFILL_ENABLED $ENV"
echo "vercel env add WORKER_CONCURRENCY $ENV"
echo ""
echo "# --- Notifications ---"
echo "vercel env add SLACK_WEBHOOK_URL $ENV"
echo "vercel env add DISCORD_WEBHOOK_URL $ENV"
echo "vercel env add RESEND_API_KEY $ENV"
echo "vercel env add ALERT_EMAIL_TO $ENV"
echo "vercel env add ALERT_EMAIL_FROM $ENV"
echo ""
echo "# --- Deployment ---"
echo "vercel env add NEXT_PUBLIC_REDIS_HOST $ENV"
echo "vercel env add DATABASE_URL $ENV"
echo "vercel env add NEXUS_URL $ENV"
